name: edu_vista
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  cloud_firestore: ^5.2.1
  cupertino_icons: ^1.0.6
  dio: ^5.7.0
  file_picker: ^8.1.2
  firebase_auth: ^5.1.4
  firebase_core: ^3.3.0
  firebase_storage: ^12.1.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6

  flutter_svg: ^2.0.10+1
  get: ^4.6.6

  paymob_payment: ^0.0.1+1
  shared_preferences: ^2.2.3
  url_launcher: ^6.3.0
  video_box:
    git:
      url: https://github.com/mahmoudelgharabawi/flutter_video_box.git
dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: PlusJakartaSans
      fonts:
        - asset: assets/fonts/PlusJakartaSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/PlusJakartaSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/PlusJakartaSans-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/PlusJakartaSans-Light.ttf
          weight: 300
        - asset: assets/fonts/PlusJakartaSans-Medium.ttf
          weight: 300
        - asset: assets/fonts/PlusJakartaSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/PlusJakartaSans-SemiBold.ttf
          weight: 600
    - family: PlaywriteCU
      fonts:
        - asset: assets/fonts/PlaywriteCU-Regular.ttf
        - asset: assets/fonts/PlaywriteCU-Thin.ttf
