// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3tdHu2nnLVxf9kI358L_g-Gh34dHuV0c',
    appId: '1:1028667050157:web:37c8ff81ec375bb2fd9e24',
    messagingSenderId: '1028667050157',
    projectId: 'edu-vista-cda7f',
    authDomain: 'edu-vista-cda7f.firebaseapp.com',
    storageBucket: 'edu-vista-cda7f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVK52tBImWg-1kuQ7hDSLV5df-vwipX1U',
    appId: '1:1028667050157:android:c27192c5a9efcafdfd9e24',
    messagingSenderId: '1028667050157',
    projectId: 'edu-vista-cda7f',
    storageBucket: 'edu-vista-cda7f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAn62o_wPkPI5anGzB-gM7ujHyJ3HVIOig',
    appId: '1:1028667050157:ios:7a37eb25dc8c9b0cfd9e24',
    messagingSenderId: '1028667050157',
    projectId: 'edu-vista-cda7f',
    storageBucket: 'edu-vista-cda7f.appspot.com',
    iosBundleId: 'com.example.eduVista',
  );
}
