class kConstants {
  static const apikey =
      "ZXlKaGJHY2lPaUpJVXpVeE1pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SmpiR0Z6Y3lJNklrMWxjbU5vWVc1MElpd2ljSEp2Wm1sc1pWOXdheUk2T1RrMU9ERTJMQ0p1WVcxbElqb2lhVzVwZEdsaGJDSjkuRzRWeXpSVFdTQjAzLWNhWF9iRjZSOG5qM3pfczVSdmIwUElnZGFrVXFyNlMzcUcwMjhjMHNfSnlRNVBmU3dmRDNFVHhYUHI4VThXUjg2TVNhYTk3QVE=";

  static const cardPaymentMethodIntegrationId = '4834299';
}
